<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        \DB::table('cities')->insert([

                ['id' => '8', 'city_title' => 'Belton', 'county_id' => '97'],
                ['id' => '9', 'city_title' => 'Gladstone', 'county_id' => '102'],
                ['id' => '12', 'city_title' => 'Basehor', 'county_id' => '2'],
                ['id' => '17', 'city_title' => 'Elmer', 'county_id' => '3'],
                ['id' => '18', 'city_title' => 'Calhoun', 'county_id' => '100'],
                ['id' => '21', 'city_title' => 'Cherokee', 'county_id' => '4'],
                ['id' => '22', 'city_title' => 'New Franklin', 'county_id' => '5'],
                ['id' => '23', 'city_title' => 'Maysville (Weatherby)', 'county_id' => '6'],
                ['id' => '25', 'city_title' => 'Cameron', 'county_id' => '7'],
                ['id' => '26', 'city_title' => 'Dover', 'county_id' => '111'],
                ['id' => '27', 'city_title' => 'Eagleville (Bethany)', 'county_id' => '112'],
                ['id' => '28', 'city_title' => 'Brunswick', 'county_id' => '8'],
                ['id' => '31', 'city_title' => 'Dawn', 'county_id' => '106'],
                ['id' => '38', 'city_title' => 'Freeman', 'county_id' => '97'],
                ['id' => '39', 'city_title' => 'Garden City', 'county_id' => '97'],
                ['id' => '41', 'city_title' => 'Bonner Springs', 'county_id' => '10'],
                ['id' => '43', 'city_title' => 'Gower', 'county_id' => '110'],
                ['id' => '47', 'city_title' => 'Lee\'s Summit (Greenwood)', 'county_id' => '97'],
                ['id' => '50', 'city_title' => 'Springfield', 'county_id' => '4'],
                ['id' => '51', 'city_title' => 'Spickard', 'county_id' => '39'],
                ['id' => '52', 'city_title' => 'Hamilton', 'county_id' => '106'],
                ['id' => '53', 'city_title' => 'Prairie Village', 'county_id' => '104'],
                ['id' => '58', 'city_title' => 'Bucyrus', 'county_id' => '67'],
                ['id' => '59', 'city_title' => 'Gravois Mills', 'county_id' => '94'],
                ['id' => '65', 'city_title' => 'Lee\'s Summit', 'county_id' => '109'],
                ['id' => '67', 'city_title' => 'Everton', 'county_id' => '82'],
                ['id' => '76', 'city_title' => 'Oregon', 'county_id' => '4'],
                ['id' => '78', 'city_title' => 'Columbia', 'county_id' => '4'],
                ['id' => '85', 'city_title' => 'Lexington', 'county_id' => '4'],
                ['id' => '86', 'city_title' => 'Paola', 'county_id' => '4'],
                ['id' => '95', 'city_title' => 'Joplin', 'county_id' => '4'],
                ['id' => '99', 'city_title' => 'Kearney', 'county_id' => '102'],
                ['id' => '107', 'city_title' => 'Atchinson', 'county_id' => '4'],
                ['id' => '108', 'city_title' => 'Lawrence', 'county_id' => '18'],
                ['id' => '109', 'city_title' => 'Buckner', 'county_id' => '109'],
                ['id' => '112', 'city_title' => 'Odessa', 'county_id' => '111'],
                ['id' => '118', 'city_title' => 'Osawotomie', 'county_id' => '19'],
                ['id' => '119', 'city_title' => 'Smithville', 'county_id' => '102'],
                ['id' => '123', 'city_title' => 'Platte City', 'county_id' => '25'],
                ['id' => '126', 'city_title' => 'Liberty (Kansas City)', 'county_id' => '102'],
                ['id' => '128', 'city_title' => 'Raymore', 'county_id' => '25'],
                ['id' => '130', 'city_title' => 'Topeka', 'county_id' => '25'],
                ['id' => '132', 'city_title' => 'Jackson', 'county_id' => '25'],
                ['id' => '133', 'city_title' => 'Racket', 'county_id' => '25'],
                ['id' => '134', 'city_title' => 'Overland Park', 'county_id' => '25'],
                ['id' => '136', 'city_title' => 'Spring Hill', 'county_id' => '104'],
                ['id' => '139', 'city_title' => 'Laurie', 'county_id' => '25'],
                ['id' => '140', 'city_title' => 'St Joe', 'county_id' => '25'],
                ['id' => '141', 'city_title' => 'Wellingrton', 'county_id' => '25'],
                ['id' => '144', 'city_title' => 'Stover', 'county_id' => '25'],
                ['id' => '146', 'city_title' => 'Grain Valley', 'county_id' => '25'],
                ['id' => '147', 'city_title' => 'Eldon', 'county_id' => '25'],
                ['id' => '149', 'city_title' => 'PERRY', 'county_id' => '4'],
                ['id' => '150', 'city_title' => 'Parkville', 'county_id' => '69'],
                ['id' => '153', 'city_title' => 'Wellington', 'county_id' => '111'],
                ['id' => '157', 'city_title' => 'Peculiar', 'county_id' => '4'],
                ['id' => '159', 'city_title' => 'Wood Heights', 'county_id' => '102'],
                ['id' => '161', 'city_title' => 'Deepwater-Brownington', 'county_id' => '100'],
                ['id' => '162', 'city_title' => 'Bosworth', 'county_id' => '95'],
                ['id' => '163', 'city_title' => 'Ottawa', 'county_id' => '21'],
                ['id' => '167', 'city_title' => 'Lawson', 'county_id' => '102'],
                ['id' => '168', 'city_title' => 'Craig', 'county_id' => '22'],
                ['id' => '169', 'city_title' => 'Kingsville', 'county_id' => '23'],
                ['id' => '170', 'city_title' => 'Tarkio', 'county_id' => '25'],
                ['id' => '174', 'city_title' => 'Topeka (Menoken)', 'county_id' => '24'],
                ['id' => '177', 'city_title' => 'Raytown', 'county_id' => '107'],
                ['id' => '178', 'city_title' => 'Dearborn', 'county_id' => '26'],
                ['id' => '181', 'city_title' => 'TRIMBLE', 'county_id' => '4'],
                ['id' => '182', 'city_title' => 'Sibley', 'county_id' => '27'],
                ['id' => '183', 'city_title' => 'Missouri City', 'county_id' => '102'],
                ['id' => '184', 'city_title' => 'Holt', 'county_id' => '110'],
                ['id' => '186', 'city_title' => 'Gardner', 'county_id' => '29'],
                ['id' => '187', 'city_title' => 'Cainsville-Ridgeway', 'county_id' => '112'],
                ['id' => '188', 'city_title' => 'LaCygne', 'county_id' => '30'],
                ['id' => '190', 'city_title' => 'Edwardsville', 'county_id' => '77'],
                ['id' => '191', 'city_title' => 'Lansing', 'county_id' => '4'],
                ['id' => '193', 'city_title' => 'Bates City', 'county_id' => '111'],
                ['id' => '194', 'city_title' => 'Carrolton', 'county_id' => '31'],
                ['id' => '196', 'city_title' => 'Winston', 'county_id' => '4'],
                ['id' => '199', 'city_title' => 'La Monte', 'county_id' => '50'],
                ['id' => '201', 'city_title' => 'Rolla', 'county_id' => '40'],
                ['id' => '203', 'city_title' => 'Marceline', 'county_id' => '4'],
                ['id' => '205', 'city_title' => 'Strausburg', 'county_id' => '97'],
                ['id' => '206', 'city_title' => 'Newburg', 'county_id' => '4'],
                ['id' => '207', 'city_title' => 'Lebanon', 'county_id' => '32'],
                ['id' => '208', 'city_title' => 'Marshall', 'county_id' => '33'],
                ['id' => '210', 'city_title' => 'McLouth', 'county_id' => '34'],
                ['id' => '211', 'city_title' => 'Hardin', 'county_id' => '113'],
                ['id' => '212', 'city_title' => 'RUSHVILLE', 'county_id' => '4'],
                ['id' => '213', 'city_title' => 'Wellington/Napolean', 'county_id' => '111'],
                ['id' => '214', 'city_title' => 'Tonganoxie', 'county_id' => '35'],
                ['id' => '219', 'city_title' => 'Jerico Springs', 'county_id' => '48'],
                ['id' => '221', 'city_title' => 'Kidder', 'county_id' => '106'],
                ['id' => '222', 'city_title' => 'Nevada', 'county_id' => '4'],
                ['id' => '227', 'city_title' => 'St. Joseph', 'county_id' => '37'],
                ['id' => '229', 'city_title' => 'Queen City', 'county_id' => '38'],
                ['id' => '230', 'city_title' => 'Mercer', 'county_id' => '39'],
                ['id' => '231', 'city_title' => 'Rocky Mount', 'county_id' => '94'],
                ['id' => '233', 'city_title' => 'Centerview (Columbus)', 'county_id' => '105'],
                ['id' => '234', 'city_title' => 'OGDEN', 'county_id' => '4'],
                ['id' => '235', 'city_title' => 'Oskaloosa', 'county_id' => '4'],
                ['id' => '236', 'city_title' => 'Rayville', 'county_id' => '4'],
                ['id' => '237', 'city_title' => 'Rae (Flag Springs)', 'county_id' => '40'],
                ['id' => '238', 'city_title' => 'Polo', 'county_id' => '106'],
                ['id' => '239', 'city_title' => 'Waverly', 'county_id' => '4'],
                ['id' => '240', 'city_title' => 'Bogard', 'county_id' => '95'],
                ['id' => '242', 'city_title' => 'Topeka (Elmont)', 'county_id' => '41'],
                ['id' => '243', 'city_title' => 'Stockton', 'county_id' => '4'],
                ['id' => '244', 'city_title' => 'Bolivar', 'county_id' => '49'],
                ['id' => '245', 'city_title' => 'King City', 'county_id' => '42'],
                ['id' => '247', 'city_title' => 'Knob Noster', 'county_id' => '4'],
                ['id' => '248', 'city_title' => 'SHAWNEE', 'county_id' => '4'],
                ['id' => '249', 'city_title' => 'St Louis', 'county_id' => '43'],
                ['id' => '250', 'city_title' => 'Kingston', 'county_id' => '106'],
                ['id' => '252', 'city_title' => 'Cainsville', 'county_id' => '44'],
                ['id' => '253', 'city_title' => 'Coffey', 'county_id' => '72'],
                ['id' => '254', 'city_title' => 'Altamont', 'county_id' => '4'],
                ['id' => '259', 'city_title' => 'DEEPWATER OR GERMANTOWN', 'county_id' => '4'],
                ['id' => '261', 'city_title' => 'Osceola (Weaubleau)', 'county_id' => '45'],
                ['id' => '263', 'city_title' => 'Blairstown', 'county_id' => '100'],
                ['id' => '269', 'city_title' => 'Edwards', 'county_id' => '87'],
                ['id' => '272', 'city_title' => 'Centerview', 'county_id' => '105'],
                ['id' => '275', 'city_title' => 'Adrian', 'county_id' => '76'],
                ['id' => '276', 'city_title' => 'Cole Camp', 'county_id' => '87'],
                ['id' => '277', 'city_title' => 'Sedalia', 'county_id' => '46'],
                ['id' => '280', 'city_title' => 'Rich Hill', 'county_id' => '47'],
                ['id' => '281', 'city_title' => 'Harrisonville (Garden City)', 'county_id' => '97'],
                ['id' => '282', 'city_title' => 'El Dorado Springs', 'county_id' => '48'],
                ['id' => '283', 'city_title' => 'Archie', 'county_id' => '97'],
                ['id' => '284', 'city_title' => 'Flemington', 'county_id' => '49'],
                ['id' => '286', 'city_title' => 'Hughesville', 'county_id' => '50'],
                ['id' => '291', 'city_title' => 'Osceola (Iconium)', 'county_id' => '88'],
                ['id' => '292', 'city_title' => 'Golden City', 'county_id' => '51'],
                ['id' => '293', 'city_title' => 'Urich (Johnstown)', 'county_id' => '76'],
                ['id' => '294', 'city_title' => 'Osceola (Lowry City)', 'county_id' => '58'],
                ['id' => '296', 'city_title' => 'Levasy', 'county_id' => '53'],
                ['id' => '297', 'city_title' => 'Kingston (Polo)', 'county_id' => '106'],
                ['id' => '299', 'city_title' => 'Lockwood', 'county_id' => '82'],
                ['id' => '302', 'city_title' => 'Deepwater (Brownington)', 'county_id' => '100'],
                ['id' => '303', 'city_title' => 'Leeton', 'county_id' => '54'],
                ['id' => '305', 'city_title' => 'Climax Springs', 'county_id' => '85'],
                ['id' => '310', 'city_title' => 'Quincy', 'county_id' => '4'],
                ['id' => '313', 'city_title' => 'Holden (Chilhowee)', 'county_id' => '105'],
                ['id' => '320', 'city_title' => 'Schell City-Taberville', 'county_id' => '75'],
                ['id' => '323', 'city_title' => 'Creighton', 'county_id' => '97'],
                ['id' => '325', 'city_title' => 'Stark', 'county_id' => '4'],
                ['id' => '326', 'city_title' => 'Urich', 'county_id' => '100'],
                ['id' => '327', 'city_title' => 'Lowry City', 'county_id' => '58'],
                ['id' => '328', 'city_title' => 'FOSTER', 'county_id' => '4'],
                ['id' => '330', 'city_title' => 'Maryville', 'county_id' => '59'],
                ['id' => '331', 'city_title' => 'Mt. Vernon', 'county_id' => '4'],
                ['id' => '339', 'city_title' => 'Warsaw', 'county_id' => '4'],
                ['id' => '340', 'city_title' => 'Drexel', 'county_id' => '4'],
                ['id' => '343', 'city_title' => 'Clinton (Leesville)', 'county_id' => '100'],
                ['id' => '345', 'city_title' => 'Appleton City', 'county_id' => '4'],
                ['id' => '347', 'city_title' => 'Clinton', 'county_id' => '100'],
                ['id' => '348', 'city_title' => 'Butler', 'county_id' => '4'],
                ['id' => '349', 'city_title' => 'Holden-Blairstown', 'county_id' => '4'],
                ['id' => '351', 'city_title' => 'Osceola', 'county_id' => '4'],
                ['id' => '352', 'city_title' => 'Rockville', 'county_id' => '87'],
                ['id' => '353', 'city_title' => 'Lenexa', 'county_id' => '104'],
                ['id' => '355', 'city_title' => 'Excelsior Springs', 'county_id' => '102'],
                ['id' => '357', 'city_title' => 'Pamona', 'county_id' => '4'],
                ['id' => '359', 'city_title' => 'Montrose', 'county_id' => '100'],
                ['id' => '360', 'city_title' => 'Riverside', 'county_id' => '60'],
                ['id' => '361', 'city_title' => 'Miami', 'county_id' => '61'],
                ['id' => '362', 'city_title' => 'Cowgill', 'county_id' => '106'],
                ['id' => '363', 'city_title' => 'Kirksville', 'county_id' => '62'],
                ['id' => '364', 'city_title' => 'Chilhowee', 'county_id' => '100'],
                ['id' => '365', 'city_title' => 'New Florence', 'county_id' => '63'],
                ['id' => '366', 'city_title' => 'Oak Grove', 'county_id' => '64'],
                ['id' => '367', 'city_title' => 'Amsterdam', 'county_id' => '4'],
                ['id' => '368', 'city_title' => 'Wellsville', 'county_id' => '65'],
                ['id' => '369', 'city_title' => 'Leavenworth', 'county_id' => '66'],
                ['id' => '371', 'city_title' => 'Osawatomie', 'county_id' => '67'],
                ['id' => '373', 'city_title' => 'Weston', 'county_id' => '69'],
                ['id' => '374', 'city_title' => 'Horton', 'county_id' => '70'],
                ['id' => '375', 'city_title' => 'Concordia', 'county_id' => '111'],
                ['id' => '376', 'city_title' => 'Mayview', 'county_id' => '111'],
                ['id' => '377', 'city_title' => 'Lincoln', 'county_id' => '87'],
                ['id' => '378', 'city_title' => 'Harris', 'county_id' => '71'],
                ['id' => '379', 'city_title' => 'Liberty-Excelsior Springs', 'county_id' => '102'],
                ['id' => '380', 'city_title' => 'Jamesport', 'county_id' => '72'],
                ['id' => '381', 'city_title' => 'Elmdale', 'county_id' => '73'],
                ['id' => '382', 'city_title' => 'Louisburg', 'county_id' => '74'],
                ['id' => '383', 'city_title' => 'Linneus', 'county_id' => '114'],
                ['id' => '384', 'city_title' => 'Talley Bend', 'county_id' => '75'],
                ['id' => '385', 'city_title' => 'Lone Jack', 'county_id' => '109'],
                ['id' => '386', 'city_title' => 'Hume', 'county_id' => '76'],
                ['id' => '388', 'city_title' => 'SWEET SPRINGS', 'county_id' => '4'],
                ['id' => '389', 'city_title' => 'Hiawatha', 'county_id' => '78'],
                ['id' => '390', 'city_title' => 'Praire Village', 'county_id' => '104'],
                ['id' => '391', 'city_title' => 'Elmira', 'county_id' => '113'],
                ['id' => '392', 'city_title' => 'Independence', 'county_id' => '79'],
                ['id' => '394', 'city_title' => 'Montrose (Germantown)', 'county_id' => '100'],
                ['id' => '395', 'city_title' => 'Deepwater', 'county_id' => '5'],
                ['id' => '396', 'city_title' => 'Fillmore', 'county_id' => '80'],
                ['id' => '398', 'city_title' => 'Springdale', 'county_id' => '81'],
                ['id' => '399', 'city_title' => 'Richmond', 'county_id' => '113'],
                ['id' => '400', 'city_title' => 'Golden City (Meinert)', 'county_id' => '82'],
                ['id' => '401', 'city_title' => 'Liberty', 'county_id' => '102'],
                ['id' => '403', 'city_title' => 'Stilwell', 'county_id' => '104'],
                ['id' => '404', 'city_title' => 'Chula', 'county_id' => '84'],
                ['id' => '405', 'city_title' => 'Macks Creek', 'county_id' => '85'],
                ['id' => '406', 'city_title' => 'Warrensburg', 'county_id' => '86'],
                ['id' => '408', 'city_title' => 'Warsaw (Quincy)', 'county_id' => '87'],
                ['id' => '409', 'city_title' => 'De Soto', 'county_id' => '104'],
                ['id' => '410', 'city_title' => 'Holden', 'county_id' => '105'],
                ['id' => '411', 'city_title' => 'Depwater (Lowry City)', 'county_id' => '88'],
                ['id' => '412', 'city_title' => 'Sheldon', 'county_id' => '89'],
                ['id' => '413', 'city_title' => 'Pleasant Hill', 'county_id' => '97'],
                ['id' => '414', 'city_title' => 'Giman City', 'county_id' => '90'],
                ['id' => '415', 'city_title' => 'Eudora', 'county_id' => '91'],
                ['id' => '416', 'city_title' => 'Tunas', 'county_id' => '92'],
                ['id' => '417', 'city_title' => 'Lathrop', 'county_id' => '110'],
                ['id' => '418', 'city_title' => 'Moberly', 'county_id' => '93'],
                ['id' => '420', 'city_title' => 'Versailles', 'county_id' => '94'],
                ['id' => '421', 'city_title' => 'Norborne', 'county_id' => '95'],
                ['id' => '423', 'city_title' => 'Macon', 'county_id' => '96'],
                ['id' => '424', 'city_title' => 'Orrick', 'county_id' => '113'],
                ['id' => '425', 'city_title' => 'Harrisonville', 'county_id' => '97'],
                ['id' => '426', 'city_title' => 'Wamego', 'county_id' => '98'],
                ['id' => '427', 'city_title' => 'Milan', 'county_id' => '99'],
                ['id' => '428', 'city_title' => 'Windsor', 'county_id' => '100'],
                ['id' => '429', 'city_title' => 'Newcomer (Mendon)', 'county_id' => '101'],
                ['id' => '432', 'city_title' => 'Bethany', 'county_id' => '112'],
                ['id' => '433', 'city_title' => 'Clarksdale', 'county_id' => '103'],
                ['id' => '434', 'city_title' => 'Olathe', 'county_id' => '104'],
                ['id' => '435', 'city_title' => 'Higginsville', 'county_id' => '111'],
                ['id' => '436', 'city_title' => 'LaTour (Rose Hill)', 'county_id' => '105'],
                ['id' => '437', 'city_title' => 'Earnestville (Concordia)', 'county_id' => '111'],
                ['id' => '438', 'city_title' => 'Polo (Sandals)', 'county_id' => '106'],
                ['id' => '439', 'city_title' => 'Kansas City', 'county_id' => '107'],
                ['id' => '440', 'city_title' => 'Blythedale (Ridgeway)', 'county_id' => '112'],
                ['id' => '441', 'city_title' => 'Platte River (Gower)', 'county_id' => '108'],
                ['id' => '442', 'city_title' => 'Blue Springs', 'county_id' => '109'],
                ['id' => '443', 'city_title' => 'Camreon', 'county_id' => '110'],
                ['id' => '446', 'city_title' => 'Plattsburg', 'county_id' => '110'],
                ['id' => '447', 'city_title' => 'Emma', 'county_id' => '111'],
                ['id' => '448', 'city_title' => 'Blue Ridge (Bethany)', 'county_id' => '112'],
                ['id' => '451', 'city_title' => 'Brookfield', 'county_id' => '114'],
                ['id' => '452', 'city_title' => 'Blackburn', 'county_id' => '115']

        ]);
    }
}
