<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        \DB::table('counties')->insert([
            ['id' => '1', 'state_id' => '2', 'county_title' => 'St Claire (OTFS)'],
            ['id' => '2', 'state_id' => '3', 'county_title' => 'Leavenwoth (OFT West)'],
            ['id' => '3', 'state_id' => '2', 'county_title' => 'Macon (OTF East)'],
            ['id' => '4', 'state_id' => '3', 'county_title' => 'Crawford (OFT South)'],
            ['id' => '5', 'state_id' => '2', 'county_title' => 'Howard (OFT East)'],
            ['id' => '6', 'state_id' => '2', 'county_title' => 'Dekalb (OFT North)'],
            ['id' => '7', 'state_id' => '2', 'county_title' => 'Bates (OFT North)'],
            ['id' => '8', 'state_id' => '2', 'county_title' => 'Chariton (OFT North)'],
            ['id' => '9', 'state_id' => '3', 'county_title' => 'Douglas (OFT West)'],
            ['id' => '10', 'state_id' => '3', 'county_title' => 'Leavenworth (OFT West)'],
            ['id' => '11', 'state_id' => '3', 'county_title' => 'Miami (OFT South)'],
            ['id' => '12', 'state_id' => '2', 'county_title' => 'Lafeyette'],
            ['id' => '13', 'state_id' => '3', 'county_title' => 'Johsnon (Johnson Ks)'],
            ['id' => '14', 'state_id' => '3', 'county_title' => 'Wyondote (OTF West)'],
            ['id' => '15', 'state_id' => '3', 'county_title' => 'Wyandotte (OFT West)'],
            ['id' => '16', 'state_id' => '2', 'county_title' => 'Jackson (West Jackson)'],
            ['id' => '17', 'state_id' => '2', 'county_title' => 'Jackson (Jackson Mo)'],
            ['id' => '18', 'state_id' => '3', 'county_title' => 'Douglas'],
            ['id' => '19', 'state_id' => '3', 'county_title' => 'Miami (Kansas South)'],
            ['id' => '20', 'state_id' => '2', 'county_title' => 'United States'],
            ['id' => '21', 'state_id' => '3', 'county_title' => 'Franklin (OFT West)'],
            ['id' => '22', 'state_id' => '2', 'county_title' => 'Holt (OFT North)'],
            ['id' => '23', 'state_id' => '2', 'county_title' => 'Johnson (Johnson, Mo)'],
            ['id' => '24', 'state_id' => '3', 'county_title' => 'Shawnee (Kansas West)'],
            ['id' => '25', 'state_id' => '3', 'county_title' => 'USA'],
            ['id' => '26', 'state_id' => '2', 'county_title' => 'Platte (OFT North)'],
            ['id' => '27', 'state_id' => '2', 'county_title' => 'United Sates5'],
            ['id' => '28', 'state_id' => '2', 'county_title' => 'CALDWELL (OTF NORTH)'],
            ['id' => '29', 'state_id' => '3', 'county_title' => 'Johnson (Johnson, KS)'],
            ['id' => '30', 'state_id' => '3', 'county_title' => 'Lin (Kansas South)'],
            ['id' => '31', 'state_id' => '2', 'county_title' => 'Carrol'],
            ['id' => '32', 'state_id' => '2', 'county_title' => 'Laclede (OFT South)'],
            ['id' => '33', 'state_id' => '2', 'county_title' => 'Saline (OFT East)'],
            ['id' => '34', 'state_id' => '3', 'county_title' => 'Jefferson'],
            ['id' => '35', 'state_id' => '3', 'county_title' => 'Leavenworth (Kansas West)'],
            ['id' => '36', 'state_id' => '2', 'county_title' => 'Clinton (OFT North)'],
            ['id' => '37', 'state_id' => '2', 'county_title' => 'Buchanan (OFT North)'],
            ['id' => '38', 'state_id' => '2', 'county_title' => 'Schuyler (OFT North)'],
            ['id' => '39', 'state_id' => '2', 'county_title' => 'Mercer (OFT North)'],
            ['id' => '40', 'state_id' => '2', 'county_title' => 'Phelps (OFT South)'],
            ['id' => '41', 'state_id' => '3', 'county_title' => 'Shawnee (OFT West)'],
            ['id' => '42', 'state_id' => '2', 'county_title' => 'Gentry (OFT North)'],
            ['id' => '43', 'state_id' => '2', 'county_title' => 'St Louis'],
            ['id' => '44', 'state_id' => '2', 'county_title' => 'Harrison'],
            ['id' => '45', 'state_id' => '2', 'county_title' => 'Hickory (OFT South)'],
            ['id' => '46', 'state_id' => '2', 'county_title' => 'Pettis (OTF East)'],
            ['id' => '47', 'state_id' => '2', 'county_title' => 'Bates'],
            ['id' => '48', 'state_id' => '2', 'county_title' => 'Cedar (OFT South)'],
            ['id' => '49', 'state_id' => '2', 'county_title' => 'Polk (OFT South)'],
            ['id' => '50', 'state_id' => '2', 'county_title' => 'Pettis (OFT East)'],
            ['id' => '51', 'state_id' => '2', 'county_title' => 'Barton (OFT South)'],
            ['id' => '52', 'state_id' => '2', 'county_title' => 'St Claire (OFT South)'],
            ['id' => '53', 'state_id' => '2', 'county_title' => 'Jackson (East)'],
            ['id' => '54', 'state_id' => '2', 'county_title' => 'Johnson'],
            ['id' => '55', 'state_id' => '2', 'county_title' => 'Benton (OFT South)'],
            ['id' => '56', 'state_id' => '2', 'county_title' => 'Bates (OTF SOUTH)'],
            ['id' => '57', 'state_id' => '2', 'county_title' => 'St. Clair'],
            ['id' => '58', 'state_id' => '2', 'county_title' => 'St Clair (OFT South)'],
            ['id' => '59', 'state_id' => '2', 'county_title' => 'Nodaway (OFT North)'],
            ['id' => '60', 'state_id' => '2', 'county_title' => 'Platte (Clay)'],
            ['id' => '61', 'state_id' => '7', 'county_title' => 'Ottawa (Oklahoma)'],
            ['id' => '62', 'state_id' => '2', 'county_title' => 'Adair (OFT North)'],
            ['id' => '63', 'state_id' => '2', 'county_title' => 'Montgomery (OFT East)'],
            ['id' => '64', 'state_id' => '2', 'county_title' => 'Jackson (East Jackson)'],
            ['id' => '65', 'state_id' => '3', 'county_title' => 'Franklin (Kansas South)'],
            ['id' => '66', 'state_id' => '3', 'county_title' => 'Leavenworth (OFTN)'],
            ['id' => '67', 'state_id' => '3', 'county_title' => 'Miami'],
            ['id' => '68', 'state_id' => '3', 'county_title' => 'Franklin'],
            ['id' => '69', 'state_id' => '2', 'county_title' => 'Platte'],
            ['id' => '70', 'state_id' => '3', 'county_title' => 'Vernon (OFT North)'],
            ['id' => '71', 'state_id' => '2', 'county_title' => 'Sullivan (OFT East)'],
            ['id' => '72', 'state_id' => '2', 'county_title' => 'Daviess (OFT North)'],
            ['id' => '73', 'state_id' => '3', 'county_title' => 'Chase (OFT West)'],
            ['id' => '74', 'state_id' => '3', 'county_title' => 'Miami (Ks South)'],
            ['id' => '75', 'state_id' => '2', 'county_title' => 'St Clair'],
            ['id' => '76', 'state_id' => '2', 'county_title' => 'Bates (OFT South)'],
            ['id' => '77', 'state_id' => '3', 'county_title' => 'Wyandotte'],
            ['id' => '78', 'state_id' => '3', 'county_title' => 'Brown'],
            ['id' => '79', 'state_id' => '2', 'county_title' => 'Jackson'],
            ['id' => '80', 'state_id' => '2', 'county_title' => 'Andrew (OFT North)'],
            ['id' => '81', 'state_id' => '1', 'county_title' => 'Washington & Benton (OFT South)'],
            ['id' => '82', 'state_id' => '2', 'county_title' => 'Dade (OFT South)'],
            ['id' => '83', 'state_id' => '3', 'county_title' => 'Wyondotte'],
            ['id' => '84', 'state_id' => '2', 'county_title' => 'Livingston (OFT North)'],
            ['id' => '85', 'state_id' => '2', 'county_title' => 'Camden (OFT South)'],
            ['id' => '86', 'state_id' => '2', 'county_title' => 'Johnson (Johnson-Mo)'],
            ['id' => '87', 'state_id' => '2', 'county_title' => 'Benton'],
            ['id' => '88', 'state_id' => '2', 'county_title' => 'St. Clair (OFT South)'],
            ['id' => '89', 'state_id' => '2', 'county_title' => 'Vernon'],
            ['id' => '90', 'state_id' => '2', 'county_title' => 'Davies (OFT North)'],
            ['id' => '91', 'state_id' => '3', 'county_title' => 'Douglas (Kansas West)'],
            ['id' => '92', 'state_id' => '2', 'county_title' => 'Dallas (OFT South)'],
            ['id' => '93', 'state_id' => '2', 'county_title' => 'Randolph (OFT North)'],
            ['id' => '94', 'state_id' => '2', 'county_title' => 'Morgan (OFT South)'],
            ['id' => '95', 'state_id' => '2', 'county_title' => 'Carroll'],
            ['id' => '96', 'state_id' => '2', 'county_title' => 'Macon (OFT North)'],
            ['id' => '97', 'state_id' => '2', 'county_title' => 'Cass'],
            ['id' => '98', 'state_id' => '3', 'county_title' => 'Patowatomie (Kansas West)'],
            ['id' => '99', 'state_id' => '2', 'county_title' => 'Sullivan (OFT North)'],
            ['id' => '100', 'state_id' => '2', 'county_title' => 'Henry'],
            ['id' => '101', 'state_id' => '2', 'county_title' => 'Chariton (OFT Noth)'],
            ['id' => '102', 'state_id' => '2', 'county_title' => 'Clay'],
            ['id' => '103', 'state_id' => '2', 'county_title' => 'Delkab (OFTN)'],
            ['id' => '104', 'state_id' => '3', 'county_title' => 'Johnson (Johnson Ks)'],
            ['id' => '105', 'state_id' => '2', 'county_title' => 'Johnson (Johnson Mo)'],
            ['id' => '106', 'state_id' => '2', 'county_title' => 'Caldwell (OFT North)'],
            ['id' => '107', 'state_id' => '2', 'county_title' => 'Jackson (Jackson West)'],
            ['id' => '108', 'state_id' => '2', 'county_title' => 'Buchannan (OFT North)'],
            ['id' => '109', 'state_id' => '2', 'county_title' => 'Jackson (Jackson East)'],
            ['id' => '110', 'state_id' => '2', 'county_title' => 'Clinton'],
            ['id' => '111', 'state_id' => '2', 'county_title' => 'Lafayette'],
            ['id' => '112', 'state_id' => '2', 'county_title' => 'Harrison (OFT North)'],
            ['id' => '113', 'state_id' => '2', 'county_title' => 'Ray'],
            ['id' => '114', 'state_id' => '2', 'county_title' => 'Linn (OFT North)'],
            ['id' => '115', 'state_id' => '2', 'county_title' => 'Laffayette/Saline (Lafeyette)']
        ]);
    }
}
